import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SearchBar from '../components/SearchBar'
import ProductCard from '../components/ProductCard'
import request from '../utils/request'
import {PRODUCT} from '../constants/api'

export async function getStaticProps() {
  const allProductData = await request(PRODUCT);
  return {
    props: {
      allProductData,
    },
  };
}
interface HomePageProps {
  allProductData : Array<{title:string,image: string,price: number,rating: object}>
}

const Home = ({allProductData}:HomePageProps) => {
  const renderProductCard = () => {
    let tempCard = []
    for (let i = 0; i<allProductData.length; i++) {
      const {title, image, price, rating} = allProductData[i]
      tempCard.push(<ProductCard
        title={title}
        image={image}
        price={price}
        rating={rating.rate}
      />)
    }
    return tempCard
  }

  return (
    <div className='w-full flex flex-col justify-center items-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-9/12 mt-4'>
        <SearchBar/>
        <div className='grid grid-cols-1 gap-y-2 gap-x-4 md:grid-cols-2 lg:grid-cols-4 w-full mt-4'>
          {renderProductCard()}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
